LC-354 refactoring send stock
lamoda/lamoda-b2b-platform.php-sdk pull request #9
Opened 2017-11-03 15:08 UTC by ustanislav

2017-11-07 13:58 UTC, Tekill requested changes

2017-11-07 13:58 UTC, Tekill commented on src/Provider/StockStateProvider.php
> +     * @param string $dcNumber
nullable

2017-11-13 13:50 UTC, Tekill approved these changes

2017-11-20 03:28 UTC, evgeniy-baba approved these changes

2017-11-24 01:01 UTC, merged

2017-11-24 15:00 UTC, pavelsavelyev commented on src/Provider/StockStateProvider.php
> +    public function buildStockDto(array $items, $dcNumber = null, $storageLocation = null)
1. Действительно ли партнёрам кому-то это может быть надо? 
2. Почему имя через сокращение?
3. Почему без стрикт тайпов? 
4. Если всё таки надо, то хотя бы коммент омжет в док блок? что это за поля такие